name = "Jurodedu"
author = "Formuna"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89a70d6cee8fe2c0b8d0f649f0b802415d70855ccd8c1ca49c9418335c7b1dab"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
